version: '2'

networks:
  kafkanet:
    driver: bridge

services:
  zookeeper:
    networks:
      - kafkanet
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
  kafka:
    networks:
      - kafkanet
    build: .
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic_test:1:1"
      KAFKA_MESSAGE_MAX_BYTES: 2000000000
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 100001200
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./consumer.properties:/opt/kafka//config/consumer.properties
     
  kafka-rest-proxy:
    networks:
      - kafkanet
    image: confluentinc/cp-kafka-rest:5.2.1
    hostname: kafka-rest-proxy
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9093
    depends_on:
      - zookeeper
      - kafka

  kafka-topics-ui:
    networks:
      - kafkanet
    image: landoop/kafka-topics-ui:0.9.4
    hostname: kafka-topics-ui
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      PROXY: "true"
    depends_on:
      - zookeeper
      - kafka
      - kafka-rest-proxy
      
  prometheus:
    networks:
      - kafkanet
    build: './prometheus'
    ports:
      - '9090:9090'

  grafana:
    networks:
      - kafkanet
    build: './grafana'
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
     
  #app:
   # image: 'producer'
    #networks:
     # - kafkanet
#
#networks:
#  kafka:
#    external:
#      name: nat
