// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package corona

object CoronaProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      corona.Warnstufe,
      corona.Values,
      corona.Corona
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cgxjb3JvbmEucHJvdG8SB3NpZGVjYXIimQEKCVdhcm5zdHVmZRIjCgZyZWdpb24YASABKAlCC+I/CBIGcmVnaW9uUgZyZWdpb
  24SGgoDZ2t6GAIgASgJQgjiPwUSA2drelIDZ2t6Eh0KBG5hbWUYAyABKAlCCeI/BhIEbmFtZVIEbmFtZRIsCgl3YXJuc3R1ZmUYB
  CABKAlCDuI/CxIJd2FybnN0dWZlUgl3YXJuc3R1ZmUibwoGVmFsdWVzEiAKBXN0YW5kGAEgASgJQgriPwcSBXN0YW5kUgVzdGFuZ
  BJDCgp3YXJuc3R1ZmVuGAIgAygLMhIuc2lkZWNhci5XYXJuc3R1ZmVCD+I/DBIKd2FybnN0dWZlblIKd2FybnN0dWZlbiJkCgZDb
  3JvbmESJwoIdHlwZV91cmwYASABKAlCDOI/CRIHdHlwZVVybFIHdHlwZVVybBIxCgV2YWx1ZRgCIAEoCzIPLnNpZGVjYXIuVmFsd
  WVzQgriPwcSBXZhbHVlUgV2YWx1ZUICWgBiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}