// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package corona

@SerialVersionUID(0L)
final case class Warnstufe(
    region: _root_.scala.Predef.String = "",
    gkz: _root_.scala.Predef.String = "",
    name: _root_.scala.Predef.String = "",
    warnstufe: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Warnstufe] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = region
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = gkz
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = name
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = warnstufe
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = region
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = gkz
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = name
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = warnstufe
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withRegion(__v: _root_.scala.Predef.String): Warnstufe = copy(region = __v)
    def withGkz(__v: _root_.scala.Predef.String): Warnstufe = copy(gkz = __v)
    def withName(__v: _root_.scala.Predef.String): Warnstufe = copy(name = __v)
    def withWarnstufe(__v: _root_.scala.Predef.String): Warnstufe = copy(warnstufe = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = region
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = gkz
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = warnstufe
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(region)
        case 2 => _root_.scalapb.descriptors.PString(gkz)
        case 3 => _root_.scalapb.descriptors.PString(name)
        case 4 => _root_.scalapb.descriptors.PString(warnstufe)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = corona.Warnstufe
}

object Warnstufe extends scalapb.GeneratedMessageCompanion[corona.Warnstufe] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[corona.Warnstufe] = this
  def merge(`_message__`: corona.Warnstufe, `_input__`: _root_.com.google.protobuf.CodedInputStream): corona.Warnstufe = {
    var __region = `_message__`.region
    var __gkz = `_message__`.gkz
    var __name = `_message__`.name
    var __warnstufe = `_message__`.warnstufe
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __region = _input__.readStringRequireUtf8()
        case 18 =>
          __gkz = _input__.readStringRequireUtf8()
        case 26 =>
          __name = _input__.readStringRequireUtf8()
        case 34 =>
          __warnstufe = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    corona.Warnstufe(
        region = __region,
        gkz = __gkz,
        name = __name,
        warnstufe = __warnstufe,
        unknownFields = if (_unknownFields__ == null) _message__.unknownFields else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[corona.Warnstufe] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      corona.Warnstufe(
        region = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        gkz = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        warnstufe = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = CoronaProto.javaDescriptor.getMessageTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = CoronaProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = corona.Warnstufe(
    region = "",
    gkz = "",
    name = "",
    warnstufe = ""
  )
  implicit class WarnstufeLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, corona.Warnstufe]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, corona.Warnstufe](_l) {
    def region: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.region)((c_, f_) => c_.copy(region = f_))
    def gkz: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.gkz)((c_, f_) => c_.copy(gkz = f_))
    def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def warnstufe: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.warnstufe)((c_, f_) => c_.copy(warnstufe = f_))
  }
  final val REGION_FIELD_NUMBER = 1
  final val GKZ_FIELD_NUMBER = 2
  final val NAME_FIELD_NUMBER = 3
  final val WARNSTUFE_FIELD_NUMBER = 4
  def of(
    region: _root_.scala.Predef.String,
    gkz: _root_.scala.Predef.String,
    name: _root_.scala.Predef.String,
    warnstufe: _root_.scala.Predef.String
  ): _root_.corona.Warnstufe = _root_.corona.Warnstufe(
    region,
    gkz,
    name,
    warnstufe
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[Warnstufe])
}
