// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: dataFormat/data.proto

package dataFormat

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stand      string        `protobuf:"bytes,1,opt,name=stand,proto3" json:"stand,omitempty"`
	Warnstufen []*Warnstufen `protobuf:"bytes,2,rep,name=warnstufen,proto3" json:"warnstufen,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataFormat_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_dataFormat_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_dataFormat_data_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetStand() string {
	if x != nil {
		return x.Stand
	}
	return ""
}

func (x *Message) GetWarnstufen() []*Warnstufen {
	if x != nil {
		return x.Warnstufen
	}
	return nil
}

type Messages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message []*Message `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
}

func (x *Messages) Reset() {
	*x = Messages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataFormat_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messages) ProtoMessage() {}

func (x *Messages) ProtoReflect() protoreflect.Message {
	mi := &file_dataFormat_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messages.ProtoReflect.Descriptor instead.
func (*Messages) Descriptor() ([]byte, []int) {
	return file_dataFormat_data_proto_rawDescGZIP(), []int{1}
}

func (x *Messages) GetMessage() []*Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Warnstufen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region    string `protobuf:"bytes,1,opt,name=Region,proto3" json:"Region,omitempty"`
	GKZ       string `protobuf:"bytes,2,opt,name=GKZ,proto3" json:"GKZ,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Warnstufe string `protobuf:"bytes,4,opt,name=Warnstufe,proto3" json:"Warnstufe,omitempty"`
}

func (x *Warnstufen) Reset() {
	*x = Warnstufen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataFormat_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Warnstufen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warnstufen) ProtoMessage() {}

func (x *Warnstufen) ProtoReflect() protoreflect.Message {
	mi := &file_dataFormat_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warnstufen.ProtoReflect.Descriptor instead.
func (*Warnstufen) Descriptor() ([]byte, []int) {
	return file_dataFormat_data_proto_rawDescGZIP(), []int{2}
}

func (x *Warnstufen) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Warnstufen) GetGKZ() string {
	if x != nil {
		return x.GKZ
	}
	return ""
}

func (x *Warnstufen) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Warnstufen) GetWarnstufe() string {
	if x != nil {
		return x.Warnstufe
	}
	return ""
}

var File_dataFormat_data_proto protoreflect.FileDescriptor

var file_dataFormat_data_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x61, 0x74, 0x61, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x22, 0x57, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x6e, 0x64, 0x12, 0x36, 0x0a, 0x0a, 0x77, 0x61, 0x72, 0x6e, 0x73, 0x74, 0x75, 0x66,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x57, 0x61, 0x72, 0x6e, 0x73, 0x74, 0x75, 0x66, 0x65, 0x6e,
	0x52, 0x0a, 0x77, 0x61, 0x72, 0x6e, 0x73, 0x74, 0x75, 0x66, 0x65, 0x6e, 0x22, 0x39, 0x0a, 0x08,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x68, 0x0a, 0x0a, 0x57, 0x61, 0x72, 0x6e, 0x73,
	0x74, 0x75, 0x66, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x47, 0x4b, 0x5a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x47, 0x4b, 0x5a, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x57, 0x61, 0x72, 0x6e, 0x73, 0x74, 0x75, 0x66, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x57, 0x61, 0x72, 0x6e, 0x73, 0x74, 0x75, 0x66,
	0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dataFormat_data_proto_rawDescOnce sync.Once
	file_dataFormat_data_proto_rawDescData = file_dataFormat_data_proto_rawDesc
)

func file_dataFormat_data_proto_rawDescGZIP() []byte {
	file_dataFormat_data_proto_rawDescOnce.Do(func() {
		file_dataFormat_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_dataFormat_data_proto_rawDescData)
	})
	return file_dataFormat_data_proto_rawDescData
}

var file_dataFormat_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dataFormat_data_proto_goTypes = []interface{}{
	(*Message)(nil),    // 0: dataFormat.Message
	(*Messages)(nil),   // 1: dataFormat.Messages
	(*Warnstufen)(nil), // 2: dataFormat.Warnstufen
}
var file_dataFormat_data_proto_depIdxs = []int32{
	2, // 0: dataFormat.Message.warnstufen:type_name -> dataFormat.Warnstufen
	0, // 1: dataFormat.Messages.message:type_name -> dataFormat.Message
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dataFormat_data_proto_init() }
func file_dataFormat_data_proto_init() {
	if File_dataFormat_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dataFormat_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataFormat_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Messages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataFormat_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Warnstufen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dataFormat_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dataFormat_data_proto_goTypes,
		DependencyIndexes: file_dataFormat_data_proto_depIdxs,
		MessageInfos:      file_dataFormat_data_proto_msgTypes,
	}.Build()
	File_dataFormat_data_proto = out.File
	file_dataFormat_data_proto_rawDesc = nil
	file_dataFormat_data_proto_goTypes = nil
	file_dataFormat_data_proto_depIdxs = nil
}
