// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package broker

object BrokerProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      broker.CloudEvent,
      broker.Any
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cgxicm9rZXIucHJvdG8SB3NpZGVjYXIiigYKCkNsb3VkRXZlbnQSLAoJaWRTZXJ2aWNlGAEgASgJQg7iPwsSCWlkU2VydmljZ
  VIJaWRTZXJ2aWNlEiMKBnNvdXJjZRgCIAEoCUIL4j8IEgZzb3VyY2VSBnNvdXJjZRIzCgxzcGVjX3ZlcnNpb24YAyABKAlCEOI/D
  RILc3BlY1ZlcnNpb25SC3NwZWNWZXJzaW9uEh0KBHR5cGUYBCABKAlCCeI/BhIEdHlwZVIEdHlwZRJUCgphdHRyaWJ1dGVzGAUgA
  ygLMiMuc2lkZWNhci5DbG91ZEV2ZW50LkF0dHJpYnV0ZXNFbnRyeUIP4j8MEgphdHRyaWJ1dGVzUgphdHRyaWJ1dGVzEjIKC2Jpb
  mFyeV9kYXRhGAYgASgMQg/iPwwSCmJpbmFyeURhdGFIAFIKYmluYXJ5RGF0YRIsCgl0ZXh0X2RhdGEYByABKAlCDeI/ChIIdGV4d
  ERhdGFIAFIIdGV4dERhdGESPQoKcHJvdG9fZGF0YRgIIAEoCzIMLnNpZGVjYXIuQW55Qg7iPwsSCXByb3RvRGF0YUgAUglwcm90b
  0RhdGESLAoJaWRTaWRlY2FyGAkgASgJQg7iPwsSCWlkU2lkZWNhclIJaWRTaWRlY2FyEiwKCWlwU2VydmljZRgKIAEoCUIO4j8LE
  glpcFNlcnZpY2VSCWlwU2VydmljZRIsCglpcFNpZGVjYXIYCyABKAlCDuI/CxIJaXBTaWRlY2FyUglpcFNpZGVjYXISLAoJdGltZ
  XN0YW1wGAwgASgJQg7iPwsSCXRpbWVzdGFtcFIJdGltZXN0YW1wGoEBCg9BdHRyaWJ1dGVzRW50cnkSGgoDa2V5GAEgASgJQgjiP
  wUSA2tleVIDa2V5Ek4KBXZhbHVlGAIgASgLMiwuc2lkZWNhci5DbG91ZEV2ZW50LkNsb3VkRXZlbnRBdHRyaWJ1dGVWYWx1ZUIK4
  j8HEgV2YWx1ZVIFdmFsdWU6AjgBGhoKGENsb3VkRXZlbnRBdHRyaWJ1dGVWYWx1ZUIGCgRkYXRhIlAKA0FueRInCgh0eXBlX3Vyb
  BgBIAEoCUIM4j8JEgd0eXBlVXJsUgd0eXBlVXJsEiAKBXZhbHVlGAIgASgMQgriPwcSBXZhbHVlUgV2YWx1ZUICWgBiBnByb3RvM
  w=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}