version: "3.5"
services:
  client:
    container_name: sensorclient
    image: golang:latest
    volumes: 
      - .:/app  
    working_dir: /app 
    ports:
      - "9000:9000"
    #command: go run ./cmd/clientMain.go
    command: go run cmd/masterHeartBeat.go
#  sidecar:
#    container_name: sidecar
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    environment:
#      POSTGRES_USER: goland
#      POSTGRES_PASSWORD: goland
#      POSTGRES_DB: goland
#  master:
#    container_name: master
#    ports:
#      - "9001:9001"
