---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sidecar
  template:
    metadata:
      labels:
        name: sidecar
    spec:
      containers:
      - name: sidecarnode
        image: digitaltwin/smesh2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
