---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Service-Mesh-Master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: master
  template:
    metadata:
      labels:
        name: master
    spec:
      containers:
      - name:
	image:tmatschinegg/smesh3
	imagePullPolicy: IfNotPresent
	ports:
	  - containerPort:9001
