// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package chat.cloudevent

object CloudeventProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      chat.cloudevent.CloudEventAttribute,
      chat.cloudevent.Warnstufen
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChBjbG91ZGV2ZW50LnByb3RvEgRjaGF0InoKE0Nsb3VkRXZlbnRBdHRyaWJ1dGUSIAoFc3RhbmQYASABKAlCCuI/BxIFc3Rhb
  mRSBXN0YW5kEkEKCndhcm5zdHVmZW4YAiADKAsyEC5jaGF0Lldhcm5zdHVmZW5CD+I/DBIKd2FybnN0dWZlblIKd2FybnN0dWZlb
  iKaAQoKV2FybnN0dWZlbhIjCgZSZWdpb24YASABKAlCC+I/CBIGcmVnaW9uUgZSZWdpb24SGgoDR0taGAIgASgJQgjiPwUSA2dLW
  lIDR0taEh0KBE5hbWUYAyABKAlCCeI/BhIEbmFtZVIETmFtZRIsCglXYXJuc3R1ZmUYBCABKAlCDuI/CxIJd2FybnN0dWZlUglXY
  XJuc3R1ZmVCCFoGLi9jaGF0YgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}